name: dl_10_tasks
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pip:
    - transformers
    - datasets
    - evaluate
    - accelerate
    - gradio
    - matplotlib
    - scikit-learn
    - pandas
    - numpy
    - seqeval
    - sentencepiece
    - soundfile
